### ISSUE TITLE
Для чего в данной ситуации используется модификатор final?

### ISSUE THREAD

**Issue by ikuchmin** [trx0eth7/car-repair-shop#1]
https://github.com/trx0eth7/car-repair-shop/blob/b8ef747a36256173b49ba2c50934b2df2acdc2a2/src/main/java/com/trx0eth7/projects/view/components/CustomerTabContent.java#L28

**Comment by axnvas** [comment]
Учту и исправлю, посмотрел: Java 8 effective final.
