### ISSUE TITLE
Переписать проект с ипользованием Spring Data

### ISSUE THREAD

**Issue by ikuchmin** [trx0eth7/car-repair-shop#2]

**Comment by axnvas** [comment]
В проекте используется Spring Boot: выбрал способ расширение родителя spring-boot-starter-parent использую 1.5.1.RELEASE версию для совместимости с vaadin v7.
Также используется vaadin-spring-boot-starter версии 1.2.0, который транзитивно включает в себя необходимые зависимости vaadin v7.
По дефолту, спринг использует сервлет Tomcat сервера.

**Comment by axnvas** [comment]
Все ссылки на использованную документацию прикрепил в README.
