### ISSUE TITLE
Зачем было создавать фасад, какую проблему он решает?

### ISSUE THREAD

**Issue by ikuchmin** [trx0eth7/car-repair-shop#3]
https://github.com/trx0eth7/car-repair-shop/blob/9a9773c2b57eba30e376b18d043721f86228ba84/src/main/java/com/trx0eth7/projects/controller/EntityController.java#L15

**Comment by axnvas** [comment]
Фасад изначально создавался с целью разделения логики контроллера (Customer, Mechanic, Order)
